development:
  dialect: "mysql"
  database: "your_target"
  host: "localhost"
  port: "33069"
  user: "root"
  password: "1"
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://root:1@(localhost:33069)/your_target?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/yt_api_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
